# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates 3D Gaussian intensity over a grid.
#'
#' @param N An integer that defines where the intensity will be calculated in the unit cube into. If N=10 then 10^3 cubes are formed.
#' @param x,y,z A vector of positions on one dimension to calculate the kernel on.
#' @param sd The standard deviation which is assumed to be the same for each dimension.
#' @return Returns a vector giving the intensity at each grid point.
#' @examples
#' set.seed(1)
#' N = 2
#' x = rnorm(5); mux=1
#' y = rnorm(5); muy=1
#' z = rnorm(5); muz=1
#' sd=1
#' normal_kernel_3d_indicator_vectorcpp(N, x, y, z, sd)
#' @export
#' @useDynLib jqmpp
#' @importFrom Rcpp sourceCpp
normal_kernel_3d_indicator_vectorcpp <- function(N, x, y, z, sd = 0.1) {
    .Call('_jqmpp_normal_kernel_3d_indicator_vectorcpp', PACKAGE = 'jqmpp', N, x, y, z, sd)
}

